### PR TITLE
Added secure_rest_swarm quickstart

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by cmoulliard** [comment]
@heiko-braun I think that we have an issue here as you have declared a snapshot. Can you have a look please -  https://travis-ci.org/obsidian-toaster/platform/builds/196608954#L2879 ?

**Comment by heiko-braun** [comment]
My bad, I've updated the quickstart to use 2017.1.1 instead

**Comment by heiko-braun** [comment]
@cmoulliard can you trigger another CI run?

**Comment by heiko-braun** [comment]
@cmoulliard Why closed?

**Pull request closed without merging**
